### ISSUE TITLE
Certificate verification failure: R3 Let's Encrypt intermediate CA has expired

### ISSUE THREAD

**Issue by Axel-otl** [DotBow/Blender-Launcher#100]
**Describe the bug**
When launching blender launcher for the first time after choosing the folder (in my case I made ~/.blender in my home directory) the program shows no available builds to download

**To Reproduce**
1. Launch Blender Launcher
2. Choose folder in home directory
3. See error

**Expected behavior**
Blender Launcher displays a list of blender builds to download

**Screenshots**
![2021-09-26_11-23](https://user-images.githubusercontent.com/68447848/134823602-811bbe36-aa3c-48fc-9f93-814b2856f036.png)

**System (please complete the following information):**
 - Operation system: voidlinux glibc  on kernel 5.13.19_1
 - Blender Launcher version: 1.14.0
 - Log file: [BL.log](https://github.com/DotBow/Blender-Launcher/files/7232254/BL.log)

**Additional context**
Running on lxqt with the awesome window manager
I am not aware if this makes a difference, but void linux uses runnit instead of systemd.

**Comment by DotBow** [comment]
Hi!

Look like something wrong with the SSL Sertificate. Can you reach the https://download.blender.org/release/ and https://builder.blender.org/download/daily/ from your browser?

<details>
<summary>Log</summary>
<br>

```
2021-09-26 13:05:46,530 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))': /pub/graphics/blender/release/
2021-09-26 13:05:46,854 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))': /pub/graphics/blender/release/
2021-09-26 13:05:47,085 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)'))': /pub/graphics/blender/release/
2021-09-26 13:05:48,228 - Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 699, in urlopen
  File "urllib3/connectionpool.py", line 382, in _make_request
  File "urllib3/connectionpool.py", line 1010, in _validate_conn
  File "urllib3/connection.py", line 411, in connect
  File "urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threads/scraper.py", line 28, in run
  File "threads/scraper.py", line 52, in get_download_links
  File "threads/scraper.py", line 143, in scrap_stable_releases
  File "urllib3/request.py", line 74, in request
  File "urllib3/request.py", line 96, in request_encode_url
  File "urllib3/poolmanager.py", line 375, in urlopen
  File "urllib3/connectionpool.py", line 783, in urlopen
  File "urllib3/connectionpool.py", line 783, in urlopen
  File "urllib3/connectionpool.py", line 783, in urlopen
  File "urllib3/connectionpool.py", line 755, in urlopen
  File "urllib3/util/retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ftp.nluug.nl', port=443): Max retries exceeded with url: /pub/graphics/blender/release/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
```

</details>

**Comment by Axel-otl** [comment]
I was able to access both sites from my browser (firefox)

**Comment by DDru** [comment]
I also find nothing on Windows 10.
There may be a reason for this: https://scotthelme.co.uk/lets-encrypt-old-root-expiration/

**Comment by Gerstmann-Bradley** [comment]
same issue on WIN10.

>There may be a reason for this: https://scotthelme.co.uk/lets-encrypt-old-root-expiration/

but this post was 3 days ago, which is before the expiring date (Sep.30th) of whatever being mentioned in that link, right?
![image](https://user-images.githubusercontent.com/55994236/135351035-2c748cdc-3bfd-4f8e-b0eb-b4b3d2d0ca01.png)

**Comment by MarcusLlewellyn** [comment]
I am also experiencing this on Windows 10 Pro (10.0.19043 Build 19043). I can also access the links to the downloads fine with Chrome, Firefox, and Edge browsers.
[BL.log](https://github.com/DotBow/Blender-Launcher/files/7255317/BL.log)

**Comment by glend1** [comment]
glad im not the only one. win 10 here.

**Comment by gadaszewski** [comment]
Same here - Windows 10. :)

**Comment by DotBow** [comment]
Could anyone please check if this link is working?
https://ftp.nluug.nl/pub/graphics/blender/release/

**Comment by glend1** [comment]
> 
> 
> Could anyone please check if this link is working? https://ftp.nluug.nl/pub/graphics/blender/release/

yup. works here. i checked bl after and it still wasn't working

**Comment by DotBow** [comment]
Please, check if this build fixes an issue:
https://drive.google.com/file/d/19dVBNiYvyZQv9BpCcrnwxw3-KAAbQNqi/view?usp=sharing

**Comment by glend1** [comment]
nope

**Comment by DotBow** [comment]
> 
> 
> nope

Can you please add a log file for new build?

**Comment by glend1** [comment]
`
2021-09-30 15:54:30,654 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)'))': /release/
2021-09-30 15:54:30,712 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)'))': /release/
2021-09-30 15:54:30,770 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)'))': /release/
2021-09-30 15:54:30,847 - Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 411, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threads\scraper.py", line 28, in run
  File "threads\scraper.py", line 52, in get_download_links
  File "threads\scraper.py", line 143, in scrap_stable_releases
  File "urllib3\request.py", line 74, in request
  File "urllib3\request.py", line 96, in request_encode_url
  File "urllib3\poolmanager.py", line 375, in urlopen
  File "urllib3\connectionpool.py", line 783, in urlopen
  File "urllib3\connectionpool.py", line 783, in urlopen
  File "urllib3\connectionpool.py", line 783, in urlopen
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='download.blender.org', port=443): Max retries exceeded with url: /release/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))


`

**Comment by DotBow** [comment]
Administrator of blender.or confirmed that the issue is related to expired certificate, I'm looking for solutions...

**Comment by DotBow** [comment]
Please, check this build (it forces to use Mozilla’s carefully curated collection of Root Certificates https://pypi.org/project/certifi/)

https://drive.google.com/file/d/19dVBNiYvyZQv9BpCcrnwxw3-KAAbQNqi/view?usp=sharing

**Comment by MarcusLlewellyn** [comment]
> Please, check this build (it forces to use Mozilla’s carefully curated collection of Root Certificates https://pypi.org/project/certifi/)
> 
> https://drive.google.com/file/d/19dVBNiYvyZQv9BpCcrnwxw3-KAAbQNqi/view?usp=sharing

I just tried this one. Still not working. :(
[BL.log](https://github.com/DotBow/Blender-Launcher/files/7262132/BL.log)

**Comment by Tilapiatsu** [comment]
Same here, I had the same issue but it still doesn't work for me too

**Comment by DDru** [comment]
It works
![screen](https://user-images.githubusercontent.com/10414783/135549029-228c409c-372d-49e7-86fc-2693c902719e.PNG)

**Comment by aforestsociety** [comment]
That seems to be the live 1.14 version. That ones still not working for me, nor the newest fix build shared by Dotbow. Here's the log from that newest fix build
[BL.log](https://github.com/DotBow/Blender-Launcher/files/7263738/BL.log)
.
![blender launcher no work](https://user-images.githubusercontent.com/76916241/135557008-027bd110-0bac-4805-affc-af9f389874df.png)

**Comment by TitusLVR** [comment]
Same, tried version 1.14.1-dev. not helped.
`2021-10-01 09:09:55,253 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)'))': /release/
2021-10-01 09:09:55,395 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)'))': /release/
2021-10-01 09:09:55,532 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)'))': /release/
2021-10-01 09:09:55,668 - Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 411, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threads\scraper.py", line 28, in run
  File "threads\scraper.py", line 52, in get_download_links
  File "threads\scraper.py", line 143, in scrap_stable_releases
  File "urllib3\request.py", line 74, in request
  File "urllib3\request.py", line 96, in request_encode_url
  File "urllib3\poolmanager.py", line 375, in urlopen
  File "urllib3\connectionpool.py", line 783, in urlopen
  File "urllib3\connectionpool.py", line 783, in urlopen
  File "urllib3\connectionpool.py", line 783, in urlopen
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='download.blender.org', port=443): Max retries exceeded with url: /release/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))
`

**Comment by NickAllan71** [comment]
I'm running Windows 10 Pro and I have the same issue.  So glad to see that this is a recognised issue and hopefully will be resolved soon.  I love this app!

**Comment by ArieLeo** [comment]
i'm also getting this issue on windows 10, Tried dev build but it doesn't help

**Comment by glend1** [comment]
> 
> 
> Please, check this build (it forces to use Mozilla’s carefully curated collection of Root Certificates https://pypi.org/project/certifi/)
> 
> https://drive.google.com/file/d/19dVBNiYvyZQv9BpCcrnwxw3-KAAbQNqi/view?usp=sharing

tried this version (the url is the same as the previous fix?) still doesn't work
[BL.log](https://github.com/DotBow/Blender-Launcher/files/7266045/BL.log)
.

**Comment by johannbl** [comment]
I had the same issue on windows 10 using 1.12. I updated to 1.14 and it's still there for me as well.

**Comment by DotBow** [comment]
OK, another attempt with custom *.pem file from here https://curl.se/docs/caextract.html

https://drive.google.com/file/d/1JxxkS21ChJXAM2B19DlNqARl6PtD8aRo/view?usp=sharing

**Comment by IlyasseL34** [comment]
> OK, another attempt with custom *.pem file from here https://curl.se/docs/caextract.html Please, check this build: https://drive.google.com/file/d/1JxxkS21ChJXAM2B19DlNqARl6PtD8aRo/view?usp=sharing

This one works for me ! 
![image](https://user-images.githubusercontent.com/58734124/135686511-f49e9e01-3dc7-462b-8d8f-e73d0fcda9a1.png)

**Comment by TitusLVR** [comment]
Confirm, it works for me too. Nice job. Спасибо.

**Comment by dshot92** [comment]
> OK, another attempt with custom *.pem file from here https://curl.se/docs/caextract.html Please, check this build: https://drive.google.com/file/d/1JxxkS21ChJXAM2B19DlNqARl6PtD8aRo/view?usp=sharing

This is working for me now. [Win10]

Thanks!

**Comment by aforestsociety** [comment]
can confirm, is working for me on Windows 10 when previous live and dev builds weren't. Awesome work everyone!

**Comment by MarcusLlewellyn** [comment]
> OK, another attempt with custom *.pem file from here https://curl.se/docs/caextract.html Please, check this build: https://drive.google.com/file/d/1JxxkS21ChJXAM2B19DlNqARl6PtD8aRo/view?usp=sharing

It lives! Can also confirm that this is working for me now. Thanks for the hard work! :)

**Comment by Axel-otl** [comment]
> OK, another attempt with custom *.pem file from here https://curl.se/docs/caextract.html Please, check this build: https://drive.google.com/file/d/1JxxkS21ChJXAM2B19DlNqARl6PtD8aRo/view?usp=sharing

Is there a linux version of this build to test?

**Comment by AnityEx** [comment]
its WORKINNG

> OK, another attempt with custom *.pem file from here https://curl.se/docs/caextract.html Please, check this build: https://drive.google.com/file/d/1JxxkS21ChJXAM2B19DlNqARl6PtD8aRo/view?usp=sharing

**Comment by DotBow** [comment]
> > OK, another attempt with custom *.pem file from here https://curl.se/docs/caextract.html Please, check this build: https://drive.google.com/file/d/1JxxkS21ChJXAM2B19DlNqARl6PtD8aRo/view?usp=sharing
> 
> Is there a linux version of this build to test?

Both win an linux stable builds will be available today or tomorrow. This fix was suggested by well known Ray molenkamp (LazyDodo) https://lists.blender.org/pipermail/bf-committers/2021-October/051169.html

**Comment by ArieLeo** [comment]
> 
> 
> OK, another attempt with custom *.pem file from here https://curl.se/docs/caextract.html Please, check this build: https://drive.google.com/file/d/1JxxkS21ChJXAM2B19DlNqARl6PtD8aRo/view?usp=sharing

Confirmed, this one work in win 10

**Comment by feerspreads** [comment]
> > > OK, another attempt with custom *.pem file from here https://curl.se/docs/caextract.html Please, check this build: https://drive.google.com/file/d/1JxxkS21ChJXAM2B19DlNqARl6PtD8aRo/view?usp=sharing
> > 
> > 
> > Is there a linux version of this build to test?
> 
> Both win an linux stable builds will be available today or tomorrow. This fix was suggested by well known Ray Molenkamp (LazyDodo) https://lists.blender.org/pipermail/bf-committers/2021-October/051169.html

This build doesn't even launch on Win10 for me. the current latest release of 1.14 does, but it also does not show any available builds, and when I replaced the exe with the one here, I get an hourglass, and a blank log file.

**Comment by DotBow** [comment]
Builds with fix for Windows and Linux available here https://github.com/DotBow/Blender-Launcher/releases/tag/v1.14.1
Note that development build will not be updated automatically!
Thanks everyone for patience and support! ❤️‍🔥

**Comment by GlareCode** [comment]
works for me too, thanks.

**Comment by DarseZSzabo** [comment]
I'm late to the party but:  

Win10....1.9.0 isn't showing downloads but 1.14.1 does.  Will stick with 1.14.1 for now
