### ISSUE TITLE
Launcher launches nothing

### ISSUE THREAD

**Issue by ArchitectMCP** [DotBow/Blender-Launcher#111]
**Describe the bug**
Software doesn't launch blender. Sometimes crashes. Can't finish downloads.

**To Reproduce**
Use software as normal. Nothing works.

**Expected behavior**
Blender launched

**Screenshots**

**System (please complete the following information):**
 - Operation system: Windows 10
 - Blender Launcher version: v1.13, v1.14, v1.14.1
 - Log file: [BL.log](https://github.com/DotBow/Blender-Launcher/files/7517707/BL.log)

**Additional context**
BL log of last failed download. Note, the first error is the error returned when it fails to launch anything.
 
2021-11-10 22:33:42,853 - Windows - Blender Launcher 1.14.1
Traceback (most recent call last):
  File "C:\Home\Repositories\Blender-Launcher\source\widgets\library_widget.py", line 105, in draw
IndexError: list index out of range
2021-11-10 22:40:27,357 - Windows - Blender Launcher 1.14.1
Traceback (most recent call last):
  File "C:\Home\Repositories\Blender-Launcher\source\widgets\library_widget.py", line 105, in draw
IndexError: list index out of range
2021-11-10 22:43:08,447 - Windows - Blender Launcher 1.14.1
Traceback (most recent call last):
  File "C:\Home\Repositories\Blender-Launcher\source\widgets\download_widget.py", line 211, in download_rename
AttributeError: 'NoneType' object has no attribute 'subversion'
2021-11-10 23:01:17,371 - Windows - Blender Launcher 1.14.1
Traceback (most recent call last):
  File "C:\Home\Repositories\Blender-Launcher\source\widgets\download_widget.py", line 211, in download_rename
AttributeError: 'NoneType' object has no attribute 'subversion'

Attached crash dumps
[CrashDumps.zip](https://github.com/DotBow/Blender-Launcher/files/7517701/CrashDumps.zip)

**Comment by DotBow** [comment]
Hi!
Are you running it from python?... The logs doesn't look like a one from the frozen app.
Try to fully cleanup the library folder, it looks like a backwards compatibility issue.

**Comment by ArchitectMCP** [comment]
I am not running it from python. It's not a library specific issue. I cleared the library assignment, and created an empty library. The only change is a complete inability to even download a blender version, and recognize it has done so.

I have, at this point, cleared the registry of entries related to configuration, tried a new library, and (successfully) manually launched previously downloaded builds. Blender Launcher is the failure point and I have no idea what else can be removed or reset to get it working. It retains a memory of some kind that leads to it performing the exact same way regardless of being removed and reinstalled. It it's not the registry, and the library is starting from nothing, where else is the program squirreling data? AppData? Program Data? Registry keys outside the entries in Software?

**Comment by DotBow** [comment]
Please, provide a path to the library and show how it looks like inside right now.

**Comment by ArchitectMCP** [comment]
![Clipboard](https://user-images.githubusercontent.com/50960819/141882237-61a38d02-9bb3-4c1f-9497-919ea33e84bc.jpg)

**Comment by DotBow** [comment]
> 
> 
> ![Clipboard](https://user-images.githubusercontent.com/50960819/141882237-61a38d02-9bb3-4c1f-9497-919ea33e84bc.jpg)

Try to use a non system drive for library, it might be an UAC issue preventing for properly reading/writing data.
Also, run a debug build to trace more info if the above solution will not work.

**Comment by ArchitectMCP** [comment]
I honestly forgot about this because the last response was so infuriating that I needed time away to avoid being rude.

To wit:

Library was always on system drive. No issues before this one. Still, moved library. No change.
The log content provided WAS FROM THE DEBUG BUILD. It gives no information that the regular build doesn't also give.

Since that, have upgraded to 1.15. The only change is that the download_widgets.py error is now given as line 207 rather than line 211, and on restart it says the failed download is damaged. I used an empty library so I have no new information on its failing to launch. I have no reason to believe anything has changed since the basic issue remains.

At the risk of being repetitive, the issue appeared after an update to 1.14. Attempting to roll back to 1.13 did not remove the problem. obviously, 1.15 also creates the same issue.

So, I ask once again, where does the program keep its data on win64? Temp files, registry, appdata, etc. A complete list. 

To be clear: Unless your request for further information is based on info I can't have because I didn't write the program and the information is not elsewhere on your git/documentation, I've already tried it. There was no further information. I provided everything there was to provide based on previously published troubleshooting documentation.

I do understand it's not reasonable to expect you to know that. Thus why I needed to take time to calm down. It's also why I'm telling you now. I don't need basic troubleshooting at this point. I am trying to perform the freshest possible install by removing all traces and any other settings that might be affecting the software.

It seems fairly trivial to say the problem is unique to my system. It's worth noting that there appears to be no difference between a Launcher download and a portable download of the same release. I'm currently preparing to do an inspection on the file content level to see if any differences exist.

**Comment by ArchitectMCP** [comment]
Addendum: Launcher believes build is damaged because rename fails. Rename fails because something in the process of generating the object info entry "subversion" fails.

It occurred to me that I hadn't done the obvious thing and parsed the code. I did that. Finding that the launcher wasn't working (in 1.15) because it expects a certain folder name format, I copied an old install from an old library. Blender Launcher was able to open this without issue. 

Given the particulars of the python error, I believe the "self.build_info" object is not being created at all. Thus the NoneType.

It should be noted that I have a new error as of 1.15:
2022-06-25 09:45:19,123 - Windows - Blender Launcher 1.15.0
Traceback (most recent call last):
  File "C:\Home\Repositories\Blender-Launcher\source\widgets\library_widget.py", line 459, in remover_started
AttributeError: 'QPushButton' object has no attribute '_setText'

This seems to be code to update the ui button "Delete" to "deleting..." while removing a damaged build. Can confirm that the button text does not change. However, this doesn't prevent BL from deleting the build. Will continue testing.

**Comment by DotBow** [comment]
HI! Sorry for a long response.

I will try to create a debug build for your case soon to trace an issue.

**Comment by DotBow** [comment]
Could you please reproduce an error step by step using [Blender_Launcher_v1.15.0_Windows_x64_DEBUG.zip](https://github.com/DotBow/Blender-Launcher/releases/download/v1.15.0/Blender_Launcher_v1.15.0_Windows_x64_DEBUG.zip) build?

Run it with following command from CMD `"Blender Launcher.exe" -debug` and send me a `Blender Launcher.log` file.

**Comment by ArchitectMCP** [comment]
Prepare for an anticlimax.
[Blender Launcher.log](https://github.com/DotBow/Blender-Launcher/files/9238766/Blender.Launcher.log).

**Comment by DotBow** [comment]
> Prepare for an anticlimax. [Blender Launcher.log](https://github.com/DotBow/Blender-Launcher/files/9238766/Blender.Launcher.log).

Hi! Thanks!

I think I found out the breaking point. Try to run build provided below (CMD `"Blender Launcher.exe" -debug`) and we will see what an actual error leads to the issue.
https://drive.google.com/file/d/18rq65hr4vTFpqD-l2CFv0X7-wrUmbW75/view?usp=sharing

**Comment by JoBilert** [comment]
Hi, i have a similar problem. When i launche the build form the last post o get the following in the log.
[Blender Launcher.log](https://github.com/DotBow/Blender-Launcher/files/9290776/Blender.Launcher.log)
g

**Comment by DotBow** [comment]
> Hi, I have a similar problem. When I launch the build from the last post, I get the following in the log. [Blender Launcher.log](https://github.com/DotBow/Blender-Launcher/files/9290776/Blender.Launcher.log) g

Hi! Thanks for report!

There is something wrong with the Blender process itself 🤔 Will be back with more info asap.

**Comment by DotBow** [comment]
> Hi, I have a similar problem. When I launch the build from the last post, I get the following in the log. [Blender Launcher.log](https://github.com/DotBow/Blender-Launcher/files/9290776/Blender.Launcher.log) g

Could you please go to console and run following command:
`C:/Blender/daily/blender-3.3.0-beta+v33.b3fc8206be42-windows.amd64-release/blender.exe -v`

**Comment by JoBilert** [comment]
I am not sure that we are talking about the same problem.
My problem is, that Blender downloads but doesn't end the extraction process, and then cannot be launched from Blender Launcher.

If I call up the directory in my Explorer (Win11) and start the blender.exe it worked so far with any version I tried.

The message from the blender.exe -v was:

Blender 3.3.0 Beta
        build date: 2022-08-08
        build time: 23:44:56
        build commit date: 2022-08-08
        build commit time: 15:37
        build hash: b3fc8206be42
        build platform: Windows
        build type: release
        build c flags: /W3 /w34062 /w34115 /w34189 /wd4018 /wd4146 /wd4065 /wd4127 /wd4181 /wd4200 /wd4244 /wd4267 /wd4305 /wd4800 /wd4828 /wd4996 /wd4661 /wd4848 /we4013 /we4133 /we4431 /w35038 /DWIN32 /D_WINDOWS /W3 /nologo /J /Gd /MP /bigobj /Zc:inline -openmp
        build c++ flags: /W3 /w34062 /w34115 /w34189 /wd4018 /wd4146 /wd4065 /wd4127 /wd4181 /wd4200 /wd4244 /wd4267 /wd4305 /wd4800 /wd4828 /wd4996 /wd4661 /wd4848 /we4013 /we4133 /we4431 /w35038 /DWIN32 /D_WINDOWS /W3  /EHsc /nologo /J /Gd /MP /EHsc /bigobj /Zc:inline /permissive- /Zc:twoPhase- -openmp /Zc:__cplusplus
        build link flags: /MACHINE:X64  /SUBSYSTEM:CONSOLE /STACK:2097152 /ignore:4049 /ignore:4217 /ignore:4221
        build system: CMake

**Comment by ArchitectMCP** [comment]
Process hangs. I ran the commands fromthe log that the process failed on
and I got the following output from my terminal:

>C:/Users/Dyson/Documents/BL_LIB_2/stable/blender-3.2.1-windows-x64/blender.exe
-v
Blender 3.2.1
        build date: 2022-07-06
        build time: 07:45:50
        build commit date: 2022-07-05
        build commit time: 15:44
        build hash: a2d59b2dac9e
        build platform: Windows
        build type: release
        build c flags: /W3 /w34062 /w34115 /w34189 /wd4018 /wd4146 /wd4065
/wd4127 /wd4181 /wd4200 /wd4244 /wd4267 /wd4305 /wd4800 /wd4828 /wd4996
/wd4661 /we4013 /we4133 /we4431 /w35038 /DWIN32 /D_WINDOWS /W3 /nologo /J
/Gd /MP /bigobj /Zc:inline -openmp
        build c++ flags: /W3 /w34062 /w34115 /w34189 /wd4018 /wd4146
/wd4065 /wd4127 /wd4181 /wd4200 /wd4244 /wd4267 /wd4305 /wd4800 /wd4828
/wd4996 /wd4661 /we4013 /we4133 /we4431 /w35038 /DWIN32 /D_WINDOWS /W3
 /EHsc /nologo /J /Gd /MP /EHsc /bigobj /Zc:inline /permissive-
/Zc:twoPhase- -openmp /Zc:__cplusplus
        build link flags: /MACHINE:X64  /SUBSYSTEM:CONSOLE /STACK:2097152
/ignore:4049 /ignore:4217 /ignore:4221
        build system: CMake

>C:/Users/Dyson/Documents/BL_LIB_2/daily/blender-3.4.0-alpha+master.1ac956a9f9de-windows.amd64-release/blender.exe
-v
Blender 3.4.0 Alpha
        build date: 2022-08-02
        build time: 00:15:35
        build commit date: 2022-08-01
        build commit time: 22:53
        build hash: 1ac956a9f9de
        build platform: Windows
        build type: release
        build c flags: /W3 /w34062 /w34115 /w34189 /wd4018 /wd4146 /wd4065
/wd4127 /wd4181 /wd4200 /wd4244 /wd4267 /wd4305 /wd4800 /wd4828 /wd4996
/wd4661 /wd4848 /we4013 /we4133 /we4431 /w35038 /DWIN32 /D_WINDOWS /W3
/nologo /J /Gd /MP /bigobj /Zc:inline -openmp
        build c++ flags: /W3 /w34062 /w34115 /w34189 /wd4018 /wd4146
/wd4065 /wd4127 /wd4181 /wd4200 /wd4244 /wd4267 /wd4305 /wd4800 /wd4828
/wd4996 /wd4661 /wd4848 /we4013 /we4133 /we4431 /w35038 /DWIN32 /D_WINDOWS
/W3  /EHsc /nologo /J /Gd /MP /EHsc /bigobj /Zc:inline /permissive-
/Zc:twoPhase- -openmp /Zc:__cplusplus
        build link flags: /MACHINE:X64  /SUBSYSTEM:CONSOLE /STACK:2097152
/ignore:4049 /ignore:4217 /ignore:4221
        build system: CMake

Log attached.

**Comment by DotBow** [comment]
@JoBilert
This is exactly what's happening.
Getting build is more complicated than it seems. Following chain executes:
download zip>extract zip>install template if necessary>read blender info>write blender info>rename folder>push build to the library UI
Something goes wrong when BL tries to read info from blender. More specifically, the blender.exe itself fails to run. The only issue I can think of is permissions aka UAC.
Need some time to figure out what else it can be.

**Comment by DotBow** [comment]
I added hook for getting output from blender process, maybe it will draw a light on the issue (same in CMD `"Blender Launcher.exe" -debug`)

https://drive.google.com/file/d/174lkPgQYRsnCVC6XxqQ0FkHuzdY9QfX_/view?usp=sharing

**Comment by ArchitectMCP** [comment]
Log attached.

Note: When run from terminal, these commands return no errors even when
error message printing is forced.

**Comment by DotBow** [comment]
I don't see any attachments

**Comment by ArchitectMCP** [comment]
[Blender Launcher.log](https://github.com/DotBow/Blender-Launcher/files/9485861/Blender.Launcher.log)
Sorry. Depression...

Here's the attachment.
