### ISSUE TITLE
Use windows certificate store when making requests

### ISSUE THREAD

**Issue by Reeley** [DotBow/Blender-Launcher#146]
**Is your feature request related to a problem? Please describe.**
When using Blender Launcher I get ``SSL: CERTIFICATE_VERIFY_FAILED`` error logged to BL.log.
This happens because we use a proxy with a self signed certificate in our network. The self signed certificate is added to the windows certificate store by our domain.
Here is an excerpt of the error:
```
2022-02-22 11:29:01,687 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)'))': /pub/graphics/blender/release/
2022-02-22 11:29:01,776 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)'))': /pub/graphics/blender/release/
2022-02-22 11:29:01,868 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)'))': /pub/graphics/blender/release/
2022-02-22 11:29:01,962 - Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 411, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threads\scraper.py", line 28, in run
  File "threads\scraper.py", line 52, in get_download_links
  File "threads\scraper.py", line 143, in scrap_stable_releases
  File "urllib3\request.py", line 74, in request
  File "urllib3\request.py", line 96, in request_encode_url
  File "urllib3\poolmanager.py", line 375, in urlopen
  File "urllib3\connectionpool.py", line 783, in urlopen
  File "urllib3\connectionpool.py", line 783, in urlopen
  File "urllib3\connectionpool.py", line 783, in urlopen
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ftp.nluug.nl', port=443): Max retries exceeded with url: /pub/graphics/blender/release/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)')))

2022-02-24 19:35:13,748 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /DotBow/Blender-Launcher/releases/latest
2022-02-24 23:37:16,250 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015FB4E37A30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /DotBow/Blender-Launcher/releases/latest
2022-02-24 23:37:24,547 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015FB4F7FC40>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /DotBow/Blender-Launcher/releases/latest
2022-02-24 23:37:24,547 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015FB4F7F340>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /DotBow/Blender-Launcher/releases/latest
2022-02-24 23:37:24,547 - Traceback (most recent call last):
  File "urllib3\connection.py", line 169, in _new_conn
  File "urllib3\util\connection.py", line 73, in create_connection
  File "socket.py", line 953, in getaddrinfo
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 353, in connect
  File "urllib3\connection.py", line 181, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000015FB4F7F610>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threads\scraper.py", line 29, in run
  File "threads\scraper.py", line 39, in get_latest_tag
  File "urllib3\request.py", line 74, in request
  File "urllib3\request.py", line 96, in request_encode_url
  File "urllib3\poolmanager.py", line 375, in urlopen
  File "urllib3\connectionpool.py", line 783, in urlopen
  File "urllib3\connectionpool.py", line 783, in urlopen
  File "urllib3\connectionpool.py", line 783, in urlopen
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /DotBow/Blender-Launcher/releases/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015FB4F7F610>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
```

**Describe the solution you'd like**
Use the windows certificate store when making requests

**Additional context**
The following library looks like it could provide this feature:
https://pypi.org/project/python-certifi-win32/

It looks like the application is working correctly regardless of the SSL error though.

**Comment by DotBow** [comment]
Hi!
Please, get the [latest dev build](https://github.com/DotBow/Blender-Launcher/discussions/126#discussioncomment-2215817)
and disable **Use Custom SSL Certificate** in settings. Let me know if it will fix an issue.

**Comment by Reeley** [comment]
Hi,
thanks for the quick reply. Seems to be working!
