### ISSUE TITLE
Global shortcut unhandled exception

### ISSUE THREAD

**Issue by ValentinN84** [DotBow/Blender-Launcher#99]
After I've set up a global hotkey (Winkey + B) I get this unhandled on the next startup. Nothing gets saved to the log file pertaining to this error. I do not know if there is a way to edit/remove the hotkey assignment without starting Blender Launcher (is there a way), the only fix I could find is downgrading to 1.13.0

OS: Windows 10
Blender Launcher 1.14.0

```
Traceback (most recent call last):
  File "pynput\keyboard\__init__.py", line 147, in parse
  File "enum.py", line 408, in __getitem__
KeyError: 'meta'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pynput\keyboard\__init__.py", line 150, in parse
ValueError: invalid literal for int() with base 10: 'meta'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 83, in <module>
  File "main.py", line 73, in main
  File "windows\main_window.py", line 144, in __init__
  File "windows\main_window.py", line 385, in draw
  File "windows\main_window.py", line 398, in setup_global_hotkeys_listener
  File "pynput\keyboard\__init__.py", line 206, in __init__
  File "pynput\keyboard\__init__.py", line 207, in <listcomp>
  File "pynput\keyboard\__init__.py", line 158, in parse
  File "pynput\keyboard\__init__.py", line 159, in <listcomp>
  File "pynput\keyboard\__init__.py", line 152, in parse
ValueError: <meta>
```

**Comment by ValentinN84** [comment]
I managed to fix my 1.14.0 installation by editing the Windows Registry keys for Blender Launcher:
Computer\HKEY_CURRENT_USER\SOFTWARE\blender_launcher\settings
Change the key named enable_quick_launch_key_seq to false

**Comment by DotBow** [comment]
Hi!

Sorry for troubles, it seems that WIN key is parsing in a wrong way, will fix asap

**Comment by DotBow** [comment]
Fixed
